# Generated by Django 4.1.1 on 2023-02-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_address_customuser_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registrationnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
