# Generated by Django 4.1.1 on 2023-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customuser_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('counselor', 'counselor'), ('manager', 'manger')], default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
