# Generated by Django 4.1.1 on 2023-02-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_customuser_role_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('counselor', 'counselor'), ('manager', 'manager')], default='patient', max_length=50),
        ),
    ]
