# Generated by Django 4.1.1 on 2023-03-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assessment',
            field=models.BooleanField(default=False),
        ),
    ]
