# Generated by Django 4.1.1 on 2023-03-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_customuser_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accept',
            field=models.BooleanField(default=True),
        ),
    ]
