# Generated by Django 4.1.1 on 2023-02-24 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.BooleanField()),
                ('Question2', models.BooleanField()),
                ('Question3', models.BooleanField()),
                ('Question4', models.BooleanField()),
                ('Question5', models.BooleanField()),
                ('Question6', models.BooleanField()),
                ('Question7', models.BooleanField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
