# Generated by Django 4.1.1 on 2023-02-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessment',
            name='Question9',
            field=models.BooleanField(default=False),
        ),
    ]
