# Generated by Django 3.1.7 on 2023-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_alter_selfassessment_question9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
