# Generated by Django 4.1.1 on 2023-02-24 14:14

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment', models.DateTimeField(blank=True, null=True, verbose_name=Account.models.CustomUser)),
                ('Counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Counselor', to=settings.AUTH_USER_MODEL)),
                ('Patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
