# Generated by Django 4.1.1 on 2023-02-25 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Counselor', '0002_alter_counselorappointment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorappointment',
            name='Counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Counselor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counselorappointment',
            name='Patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
