# Generated by Django 3.1.7 on 2023-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0003_alter_counselorappointment_counselor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorappointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
