# Generated by Django 4.1.1 on 2023-03-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0003_alter_counselorappointment_counselor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorappointment',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counselorappointment',
            name='Status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
