# Generated by Django 4.1.1 on 2023-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0005_rename_patients_counselorappointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorappointment',
            name='Status',
        ),
        migrations.AddField(
            model_name='counselorappointment',
            name='Accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counselorappointment',
            name='AssigntoDoctor',
            field=models.BooleanField(default=False),
        ),
    ]
