# Generated by Django 4.1.1 on 2023-03-17 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Counselor', '0006_remove_counselorappointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorappointment',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assinged_Doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
