# Generated by Django 4.1.1 on 2023-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0007_counselorappointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorappointment',
            name='RejectedByPatient',
            field=models.BooleanField(default=False),
        ),
    ]
