# Generated by Django 4.1.1 on 2023-03-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_alter_doctorappointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='Status',
            new_name='Accept',
        ),
    ]
